import { range } from 'lodash'

const COLORS = {
  WHITE: "#ffffff",
  ORANGE: "#ebb434",
  YELLOW: "#fcff4d",
  CAMOUFLAGE: "#50ad24",
  PURPLE: "#9025c2",
  BLUE: "#00bfff",
  BROWN: "#6e3c08",
  RED: "#eb4034",
  DARK_RED: "#570505",
  BLACK: "#000000",
}


export default {
  1: {
    label: 'White Belt',
    backgroundColor: COLORS.WHITE,
    textColor: COLORS.BLACK,
    intervals: [3, 4, 7, 11],
    numberOfQuestions: 10,
    range: range(60, 75),
    sequenceRate: 0, // Probability that a sequence will be played vs. two notes simultaneously
  },
  2: {
    label: 'Orange Belt',
    backgroundColor: COLORS.ORANGE,
    textColor: COLORS.BLACK,
    intervals: [-7, -4, -3, -1, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    numberOfQuestions: 10,
    range: range(55, 75),
    sequenceRate: 0.8,
  },
  3: {
    label: 'Yellow Belt',
    backgroundColor: COLORS.YELLOW,
    textColor: COLORS.BLACK,
    intervals: range(-15, 15),
    numberOfQuestions: 10,
    range: range(55, 93),
    sequenceRate: 0.7,
  },
  4: {
    label: 'Camouflage Belt',
    backgroundColor: COLORS.CAMOUFLAGE,
    textColor: COLORS.BLACK,
    intervals: range(-15, 15),
    numberOfQuestions: 10,
    range: range(55, 93),
    sequenceRate: 0.7,
  },
  5: {
    label: 'Purple Belt',
    backgroundColor: COLORS.PURPLE,
    textColor: COLORS.WHITE,
    intervals: range(-15, 15),
    numberOfQuestions: 10,
    range: range(55, 93),
    sequenceRate: 0.7,
  },
  6: {
    label: 'Blue Belt',
    backgroundColor: COLORS.BLUE,
    textColor: COLORS.WHITE,
    intervals: range(-15, 15),
    numberOfQuestions: 10,
    range: range(55, 93),
    sequenceRate: 0.7,
  },
  7: {
    label: 'Brown Belt',
    backgroundColor: COLORS.BROWN,
    textColor: COLORS.WHITE,
    intervals: range(-15, 15),
    numberOfQuestions: 10,
    range: range(55, 93),
    sequenceRate: 0.7,
  },
  8: {
    label: 'Red Belt',
    backgroundColor: COLORS.RED,
    textColor: COLORS.WHITE,
    intervals: range(-15, 15),
    numberOfQuestions: 10,
    range: range(55, 93),
    sequenceRate: 0.7,
  },
  9: {
    label: 'Red/Black Belt',
    backgroundColor: COLORS.DARK_RED,
    textColor: COLORS.WHITE,
    intervals: range(-15, 15),
    numberOfQuestions: 10,
    range: range(55, 93),
    sequenceRate: 0.7,
  },
  10: {
    label: 'Black Belt',
    backgroundColor: COLORS.BLACK,
    textColor: COLORS.WHITE,
    intervals: range(-15, 15),
    numberOfQuestions: 10,
    range: range(55, 93),
    sequenceRate: 0.7,
  },
}
