export const violinSounds = {
  55: require('../assets/instruments/violin/violin_G3.mp3'),
  56: require('../assets/instruments/violin/violin_Gs3.mp3'),
  57: require('../assets/instruments/violin/violin_A3.mp3'),
  58: require('../assets/instruments/violin/violin_As3.mp3'),
  59: require('../assets/instruments/violin/violin_B3.mp3'),
  60: require('../assets/instruments/violin/violin_C4.mp3'),
  61: require('../assets/instruments/violin/violin_Cs4.mp3'),
  62: require('../assets/instruments/violin/violin_D4.mp3'),
  63: require('../assets/instruments/violin/violin_Ds4.mp3'),
  64: require('../assets/instruments/violin/violin_E4.mp3'),
  65: require('../assets/instruments/violin/violin_F4.mp3'),
  66: require('../assets/instruments/violin/violin_Fs4.mp3'),
  67: require('../assets/instruments/violin/violin_G4.mp3'),
  68: require('../assets/instruments/violin/violin_Gs4.mp3'),
  69: require('../assets/instruments/violin/violin_A4.mp3'),
  70: require('../assets/instruments/violin/violin_As4.mp3'),
  71: require('../assets/instruments/violin/violin_B4.mp3'),
  72: require('../assets/instruments/violin/violin_C5.mp3'),
  73: require('../assets/instruments/violin/violin_Cs5.mp3'),
  74: require('../assets/instruments/violin/violin_D5.mp3'),
  75: require('../assets/instruments/violin/violin_Ds5.mp3'),
  76: require('../assets/instruments/violin/violin_E5.mp3'),
  77: require('../assets/instruments/violin/violin_F5.mp3'),
  78: require('../assets/instruments/violin/violin_Fs5.mp3'),
  79: require('../assets/instruments/violin/violin_G5.mp3'),
  80: require('../assets/instruments/violin/violin_Gs5.mp3'),
  81: require('../assets/instruments/violin/violin_A5.mp3'),
  82: require('../assets/instruments/violin/violin_As5.mp3'),
  83: require('../assets/instruments/violin/violin_B5.mp3'),
  84: require('../assets/instruments/violin/violin_C6.mp3'),
  85: require('../assets/instruments/violin/violin_Cs6.mp3'),
  86: require('../assets/instruments/violin/violin_D6.mp3'),
  87: require('../assets/instruments/violin/violin_Ds6.mp3'),
  88: require('../assets/instruments/violin/violin_E6.mp3'),
  89: require('../assets/instruments/violin/violin_F6.mp3'),
  90: require('../assets/instruments/violin/violin_Fs6.mp3'),
  91: require('../assets/instruments/violin/violin_G6.mp3'),
  92: require('../assets/instruments/violin/violin_Gs6.mp3'),
  93: require('../assets/instruments/violin/violin_A6.mp3'),
}

export default {
  violin: violinSounds,
}